version: '3.2'

services:
  database:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: dev@dev.dev
      PGADMIN_DEFAULT_PASSWORD: dev
    ports:
      - 8080:80
