FROM node:12

# ARG ХОСТ ДБ

WORKDIR /app

RUN npm install -g typescript ts-node

COPY package.json ./
COPY yarn.lock ./

RUN yarn install

COPY . .

EXPOSE 7000

# CMD [ "ts-node", "src/index.ts" ]
CMD ["yarn", "run", "dev"]
